/**
 * Philippine-specific data for dropdowns
 */

// Philippine Banks
export const PH_BANKS = [
  "Banco de Oro (BDO)",
  "Bank of the Philippine Islands (BPI)",
  "Philippine National Bank (PNB)",
  "Metrobank",
  "Security Bank",
  "UnionBank",
  "China Banking Corporation",
  "Maybank",
  "RCBC",
  "Landbank",
  "DBP",
  "BDO Unibank",
  "Robinsons Bank",
];

// E-Wallet Providers
export const EWALLETS = [
  "GCash",
  "Maya",
  "PayMaya",
  "Coins.ph",
];

// Major Philippine Cities
export const PH_CITIES = [
  // NCR (Metro Manila)
  "Quezon City",
  "Manila",
  "Caloocan",
  "Las Piñas",
  "Makati",
  "Mandaluyong",
  "Marikina",
  "Muntinlupa",
  "Navotas",
  "Parañaque",
  "Pasay",
  "Pasig",
  "San Juan",
  "Taguig",
  "Valenzuela",
  "Malabon",
  "Pateros",
  "Antipolo",
  "Angono",
  "Cainta",
  "Morong",
  "Tanay",
  "Taytay",
  "Binangonan",
  "Baras",
  "Jala-Jala",
  "Pililla",
  "Rodriguez",
  "Bacoor",
  "Cavite City",
  "Dasmariñas",
  "Kawit",
  "Rosario",
  "Silang",
  "Tagaytay",
  "Imus",
  "Magallanes",
  "Maragondon",
  "Mendez",
  "Naic",
  "Noveleta",
  "Rosario",
  "Salawag",
  "Ternate",
  "Trece Martires",
  "Zapote",
  
  // Calabarzon
  "Batangas City",
  "Lipa",
  "Tanauan",
  "Laguna",
  "Santa Rosa",
  "Biñan",
  "Cabuyao",
  "Calamba",
  "Kawit",
  "Silang",
  "Tagaytay",
  "Lucena",
  "Quezon",
  "Tayabas",
  "Cabanatuan",
  "Gapan",
  "San Fernando",
  "Cabanatuan City",
  
  // Visayas
  "Cebu City",
  "Mandaue",
  "Lapu-Lapu",
  "Talisay",
  "Danao",
  "Iloilo City",
  "Bacolod",
  "Dumaguete",
  "Tacloban",
  "Ormoc",
  "Calinog",
  "Roxas",
  "Kalibo",
  
  // Mindanao
  "Davao City",
  "Cagayan de Oro",
  "Zamboanga City",
  "General Santos",
  "Butuan",
  "Iligan",
  "Marawi",
  "Cotabato City",
  "Surigao City",
  "Dipolog",
  "Pagadian",
  "Ozamiz",
  "Misamis Oriental",
  
  // Luzon
  "Baguio",
  "Dagupan",
  "Laoag",
  "Vigan",
  "Cabanatuan",
  "Lingayen",
  "San Fernando",
  "Tarlac City",
  "Malolos",
  "Meycauayan",
  "Marilao",
  "Obando",
  "Bocaue",
  "Bulacan",
  "Cabanatuan",
  "Gapan",
  "Muñez",
  "Palayan",
  "San Fernando",
  "Cabanatuan City",
  "Tuguegarao",
  "Santiago",
  "Bayombong",
  "Ilagan",
  "Cauayan",
  "Echague",
  "San Mateo",
  "Solano",
  "Bambang",
  "Aritao",
  "Cabarroguis",
  "Quirino",
  "Tabuk",
  "Kalinga",
  "Bontoc",
  "Mountain Province",
  "Ifugao",
  "Banaue",
  "Lagawe",
  "Kiangan",
  "Tinoc",
  "Hungduan",
  "Asipulo",
  "Mayoyao",
  "Nueva Vizcaya",
  "Bayombong",
  "Cabarroguis",
  "Aritao",
  "Solano",
  "Bambang",
  "Dupax del Sur",
  "Dupax del Norte",
  "Kasibu",
  "Santa Fe",
  "Quezon",
  "Ifugao",
  "Banaue",
  "Lagawe",
  "Kiangan",
  "Tinoc",
  "Hungduan",
  "Asipulo",
  "Mayoyao",
  "Batanes",
  "Basco",
  "Ilocos Norte",
  "Laoag",
  "Batac",
  "Paoay",
  "Pasuquin",
  "Ilocos Sur",
  "Vigan",
  "Candon",
  "Santa Maria",
  "Bantay",
  "Narvacan",
  "Caoayan",
  "Magsingal",
  "San Esteban",
  "Salcedo",
  "Sinait",
  "Tagudin",
  "La Union",
  "San Fernando",
  "Dagupan",
  "Pangasinan",
  "Lingayen",
  "Dagupan",
  "Alaminos",
  "Cabanatuan",
  "Tarlac",
  "Tarlac City",
  "San Fernando",
  "Malolos",
  "Bulacan",
  "Meycauayan",
  "Marilao",
  "Obando",
  "Bocaue",
  "Angat",
  "Balagtas",
  "Baliuag",
  "Bustos",
  "Calumpit",
  "Doña Remedios Trinidad",
  "Guiguinto",
  "Hagonoy",
  "Hermosa",
  "Hilongos",
  "Lolomboy",
  "Marilao",
  "Meycauayan",
  "Minuyan",
  "Norzagaray",
  "Obando",
  "Pandi",
  "Paombong",
  "Plaridel",
  "Pulilan",
  "Quezon",
  "Rodriguez",
  "San Ildefonso",
  "San Miguel",
  "San Rafael",
  "Santa Maria",
  "Sapang Palay",
  "Tagaytay",
  "Valenzuela",
  "Zambales",
  "Olongapo",
  "Subic",
  "Masinloc",
  "Palauig",
  "Iba",
  "Candelaria",
  "Castillejos",
  "Cabanauan",
  "Dinalupihan",
  "Gapan",
  "Guimba",
  "Jaen",
  "Laur",
  "Muñez",
  "Palayan",
  "Peñaranda",
  "San Antonio",
  "San Fernando",
  "San Isidro",
  "Santo Domingo",
  "Talugtug",
  "Talugtug",
  "Tayabas",
  "Tayabas City",
  "Quezon",
  "Candelaria",
  "Catanauan",
  "Dolores",
  "General Nakar",
  "Infanta",
  "Jomalig",
  "Lucban",
  "Lucena",
  "Macalelon",
  "Mauban",
  "Mulanay",
  "Nakar",
  "Pagbilao",
  "Panumalaan",
  "Patnanungan",
  "Polillo",
  "Real",
  "Sampaloc",
  "San Andres",
  "San Antonio",
  "Sariaya",
  "Tagkawayan",
  "Tayabas",
  "Tiaong",
  "Unisan",
  "Atimonan",
  "Gumaca",
  "Plaridel",
  "Quezon City",
  "Rizal",
  "Antipolo",
  "Angono",
  "Baras",
  "Binangonan",
  "Cainta",
  "Jala-Jala",
  "Morong",
  "Pililla",
  "Rodriguez",
  "Tanay",
  "Taytay",
  "Cavite",
  "Bacoor",
  "Cavite City",
  "Dasmariñas",
  "Kawit",
  "Rosario",
  "Silang",
  "Tagaytay",
  "Imus",
  "Magallanes",
  "Maragondon",
  "Mendez",
  "Naic",
  "Noveleta",
  "Salawag",
  "Ternate",
  "Trece Martires",
  "Zapote",
  "Laguna",
  "Santa Rosa",
  "Biñan",
  "Cabuyao",
  "Calamba",
  "Kawit",
  "Laguna",
  "Los Baños",
  "Majayjay",
  "Pakil",
  "Pagsanjan",
  "Pangil",
  "Siniloan",
  "Sta. Cruz",
  "Sta. Maria",
  "Cavinti",
  "Famy",
  "Lumban",
  "Mabitac",
  "Magdalo",
  "Paete",
  "Sampaloc",
  "Batangas",
  "Batangas City",
  "Lipa",
  "Tanauan",
  "Agoncillo",
  "Alitagtag",
  "Balete",
  "Balayan",
  "Bauan",
  "Calatagan",
  "Cuenca",
  "Ibaan",
  "Lemery",
  "Lian",
  "Mabini",
  "Malvar",
  "Mataasnakahoy",
  "Nasugbu",
  "Padre Garcia",
  "Rosario",
  "San Juan",
  "San Luis",
  "San Nicolas",
  "San Pascual",
  "Santa Teresita",
  "Taal",
  "Talisay",
  "Taysan",
  "Tingloy",
  "Tuy",
  "Quezon",
  "Candelaria",
  "Catanauan",
  "Dolores",
  "General Nakar",
  "Infanta",
  "Jomalig",
  "Lucban",
  "Lucena",
  "Macalelon",
  "Mauban",
  "Mulanay",
  "Nakar",
  "Pagbilao",
  "Panumalaan",
  "Patnanungan",
  "Polillo",
  "Real",
  "Sampaloc",
  "San Andres",
  "San Antonio",
  "Sariaya",
  "Tagkawayan",
  "Tayabas",
  "Tiaong",
  "Unisan",
  "Atimonan",
  "Gumaca",
  "Plaridel",
];

// Provinces
export const PH_PROVINCES = [
  "Abra",
  "Agusan del Norte",
  "Agusan del Sur",
  "Aklan",
  "Albay",
  "Antique",
  "Apayao",
  "Aurora",
  "Basilan",
  "Bataan",
  "Batanes",
  "Batangas",
  "Benguet",
  "Biliran",
  "Bohol",
  "Bukidnon",
  "Bulacan",
  "Calamianes",
  "Camarines Norte",
  "Camarines Sur",
  "Camiguin",
  "Capiz",
  "Catanduanes",
  "Cavite",
  "Cebu",
  "Compostela Valley",
  "Cotabato",
  "Davao del Norte",
  "Davao del Sur",
  "Davao Oriental",
  "Dinagat Islands",
  "Dinalupihan",
  "Eastern Samar",
  "Guimaras",
  "Ifugao",
  "Ilocos Norte",
  "Ilocos Sur",
  "Iloilo",
  "Isabela",
  "Kalinga",
  "Laguna",
  "Lanao del Norte",
  "Lanao del Sur",
  "La Union",
  "Leyte",
  "Maguindanao",
  "Marinduque",
  "Masbate",
  "Mindoro Occidental",
  "Mindoro Oriental",
  "Misamis Occidental",
  "Misamis Oriental",
  "Mountain Province",
  "Negros Occidental",
  "Negros Oriental",
  "Northern Samar",
  "Nueva Ecija",
  "Nueva Vizcaya",
  "Palawan",
  "Pampanga",
  "Pangasinan",
  "Quezon",
  "Quirino",
  "Rizal",
  "Romblon",
  "Samar",
  "Sarangani",
  "Siquijor",
  "Sorsogon",
  "South Cotabato",
  "Southern Leyte",
  "Sultan Kudarat",
  "Sulu",
  "Surigao del Norte",
  "Surigao del Sur",
  "Tarlac",
  "Tawi-Tawi",
  "Zambales",
  "Zamboanga del Norte",
  "Zamboanga del Sur",
  "Zamboanga Sibugay",
];

// Regions
export const PH_REGIONS = [
  "Region I (Ilocos Region)",
  "Region II (Cagayan Valley)",
  "Region III (Central Luzon)",
  "Region IV-A (CALABARZON)",
  "Region IV-B (MIMAROPA)",
  "Region V (Bicol Region)",
  "Region VI (Western Visayas)",
  "Region VII (Central Visayas)",
  "Region VIII (Eastern Visayas)",
  "Region IX (Zamboanga Peninsula)",
  "Region X (Northern Mindanao)",
  "Region XI (Davao Region)",
  "Region XII (SOCCSKSARGEN)",
  "Region XIII (Caraga)",
  "NCR (National Capital Region)",
  "CAR (Cordillera Administrative Region)",
  "ARMM (Autonomous Region in Muslim Mindanao)",
];
